spring:
  application:
    name: githls
  threads:
    virtual:
      enabled: true
logging:
  level:
    root: INFO
    io.github.kw00.githls: DEBUG
    org.springframework: WARN
github:
  api-token: null
  api-base: "https://api.github.com"
